		<section id="main_content">

		<?php if ($messages = $this->flashMessenger()->render()): ?>
			<div class="box_main box_full_width person_biography content_text">
				<div class="box_content box_content_padding user_text flashmessages">
					<?php echo $messages; ?>
				</div>
			</div>
		<?php endif; ?>

			<div class="box_main box_full_width box_with_header_and_share content_text page_register">

				<h2 class="title">Logowanie</h2>

				<div class="content">

					<div class="content_left">


						<div class="container">
							<div class="tt_form">
							<?php
								$form = $this->loginForm;
								$form->prepare();
								$form->setAttribute('action', $this->url('zfcuser/login'));
								$form->setAttribute('method', 'post');
								echo $this->form()->openTag($form)
							?>

								<?php echo $this->formElementErrors($form->get('identity')) ?>

									<div class="row">
										<?php echo $this->formLabel($form->get('identity')) ?>
										<?php echo $this->formInput($form->get('identity')) ?>
									</div>
									<div class="row">
										<?php echo $this->formLabel($form->get('credential')) ?>
										<?php echo $this->formInput($form->get('credential')) ?>
									</div>

									<?php if ($this->redirect): ?>
										<input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
									<?php endif ?>

									<div class="row">
										<?php echo $this->formButton($form->get('submit')) ?>
									</div>

								<?php echo $this->form()->closeTag() ?>

							</div>
						</div>
					</div>

					<div class="content_right">
						<div class="content_right_top">
							<div class="container user_text">
								<h4>Zaloguj się błyskawicznie</h4>
								<a href="/user/login/facebook"><img src="/img/fb_big.png" alt="TerazTeatr.pl facebook" /></a>
								<p class="roles">Logując się poprzez konto Facebook akceptujesz<br/><a href="/zasady/regulamin" target="_blank">regulamin</a> i <a href="/zasady/polityka-prywatnosci" target="_blank">politykę prywatności</a> TeatrTeatr.pl</p>
							</div>
						</div>

						<div class="content_right_bottom">
							<div class="container user_text">
								<h2>Załóż konto i ciesz się dostępem do społeczności tworzonej przez artystów, teatry i użytkowników.</h2>
								<p>
								Teraz Teatr to:<br/>
- znani artyści i nowe twarze<br/>
- repertuary na każdy dzień<br/>
- promocje dla widzów<br/>
- oraz najnowsze premiery<br/>
<br/>
Zaglądaj codziennie, ponieważ tutaj TEATR jest dla ludzi.
								</p>
							</div>
						</div>
					</div>

				</div>
			<?php /* if ($this->enableRegistration) : ?>
				<div>
				<?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
				</div>
			<?php endif; */ ?>
			</div>

		</section>
