		<section id="main_content">

			<div class="box_main box_full_width box_with_header_and_share content_text page_register">

				<h2 class="title">Rejestracja</h2>

				<div class="content">

					<div class="content_left">
						<div class="container">
							<div class="tt_form">
							<?php
								if (!$this->enableRegistration) {
									print "Registration is disabled";
									return;
								}
								$form = $this->registerForm;
								$form->prepare();
								$form->setAttribute('action', $this->url('zfcuser/register'));
								$form->setAttribute('method', 'post');
							?>

							<?php echo $this->form()->openTag($form) ?>

								<?php foreach ($form as $element): ?>
									<?php if (!($element instanceof Zend\Form\Element\Button) && !($element instanceof Zend\Form\Element\Checkbox)): ?>
									<div class="row">
										<?php echo $this->formLabel($element) ?>
									<?php endif ?>
									<?php if ($element instanceof Zend\Form\Element\Button): ?>
									<div class="row">
										<?php echo $this->formButton($element) ?>
									</div>
									<?php elseif ($element instanceof Zend\Form\Element\Checkbox): ?>
									<div class="row checkbox">
										<?php echo $this->formCheckbox($element) . $this->formLabel($element) . $this->formElementErrors($element) ?>
									</div>
									<?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
										<?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?>
									</div>
									<?php else: ?>
										<?php echo $this->formInput($element) . $this->formElementErrors($element) ?>
									</div>
									<?php endif ?>
								<?php endforeach ?>

								<?php if ($this->redirect): ?>
									<input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
								<?php endif ?>

								<?php echo $this->form()->closeTag($form) ?>

							</div>
						</div>
					</div>

					<div class="content_right">
						<div class="content_right_top">
							<div class="container user_text">
								<h4>Zaloguj się błyskawicznie</h4>
								<a href="/user/login/facebook"><img src="/img/fb_big.png" alt="TerazTeatr.pl facebook" /></a>
								<p class="roles">Logując się poprzez konto Facebook akceptujesz<br/><a href="/zasady/regulamin" target="_blank">regulamin</a> i <a href="/zasady/polityka-prywatnosci" target="_blank">politykę prywatności</a> TeatrTeatr.pl</p>
							</div>
						</div>

						<div class="content_right_bottom">
							<div class="container user_text">
								<h2>Załóż konto i ciesz się dostępem do społeczności tworzonej przez artystów, teatry i użytkowników.</h2>
								<p>
								Teraz Teatr to:<br/>
- znani artyści i nowe twarze<br/>
- repertuary na każdy dzień<br/>
- promocje dla widzów<br/>
- oraz najnowsze premiery<br/>
<br/>
Zaglądaj codziennie, ponieważ tutaj TEATR jest dla ludzi.
								</p>
							</div>
						</div>
					</div>

				</div>

		</section>