		<section id="main_content">

			<div class="box_main box_full_width box_with_header_and_share content_text page_register">

				<h2 class="title">Logowanie</h2>

				<div class="content">

					<div class="content_left">
						<div class="container">
							<div class="tt_form">
							<?php
								if (!$this->enableRegistration) {
									print "Registration is disabled";
									return;
								}
								$form = $this->registerForm;
								$form->prepare();
								$form->setAttribute('action', $this->url('zfcuser/register'));
								$form->setAttribute('method', 'post');
							?>

							<?php echo $this->form()->openTag() ?>

								<?php foreach ($form as $element): ?>
									<?php if (!$element instanceof Zend\Form\Element\Button): ?>
									<div class="row">
										<?php echo $this->formLabel($element) ?>
									<?php endif ?>
									<?php if ($element instanceof Zend\Form\Element\Button): ?>
									<div class="row">
										<?php echo $this->formButton($element) ?>
									</div>
									<?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
										<?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?>
									</div>
									<?php else: ?>
										<?php echo $this->formInput($element) . $this->formElementErrors($element) ?>
									</div>
									<?php endif ?>
								<?php endforeach ?>

								<?php if ($this->redirect): ?>
									<input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
								<?php endif ?>

								<?php echo $this->form()->closeTag() ?>

							</div>
						</div>
					</div>

					<div class="content_right">
						<div class="content_right_top">
							<div class="container user_text">
								<h4>Super tekst</h4>
								<a href="#"><img src="/img/fb_big.png" alt="" /></a>
								<p>Dajesz dajesz reko gadzeta</p>
							</div>
						</div>

						<div class="content_right_bottom">
							<div class="container user_text">
								<h2>dlaczego warto założyć konto?</h2>
								<p>
								Bo coś<br />
								Boś coś innego super<br />
								Bo niespodzianka
								</p>
							</div>
						</div>
					</div>

				</div>
			<?php if ($this->enableRegistration) : ?>
				<div>
				<?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
				</div>
				<?php endif; ?>
			</div>

		</section>